# Используйте hex, minimessage
# hex - https://minecraft.menu/minecraft-rgb-generator
# minimessage - https://webui.advntr.dev/
message-format: "hex"

messages:
  delay-start: "&6FCE &8■ &aДо начала ивента: &6%hours% ч. %minutes% мин. %seconds% сек. &aПредмет: &6%item%"
  delay-end: "&6FCE &8■ &aДо конца ивента: &6%hours% ч. %minutes% мин. %seconds% сек. &aПредмет: &6%item%"
  no-event: "&6FCE &8■ &cСейчас нет активного ивента!"
  no-items: "&6FCE &8■ &cУ вас нет &6%item%!"
  collected: "&6FCE &8■ &aВы сдали &6%amount% &a%item%! Осталось: &6%remaining%"
  reload: "&6FCE &8■ &aКонфигурация перезагружена!"
  no-perm: "&6FCE &8■ &cУ вас нет прав!"
  already-active: "&6FCE &8■ &cИвент уже активен!"
  not-active: "&6FCE &8■ &cИвент сейчас не активен!"
  event-started: "&6FCE &8■ &aИвент успешно запущен!"
  event-stopped: "&6FCE &8■ &aИвент успешно остановлен!"
  help:
    - "&e=== &6FastCollectEvent Помощь &e==="
    - "&a/%label% delay &7- Показать время до начала/конца ивента"
    - "&a/%label% top &7- Показать топ игроков"
    - "&a/%label% collect &7- Сдать предметы для ивента"
    - "&e======================"
  score-usage: "&6FCE &8■ &cИспользование: /%label% score <plus/minus> <игрок> <число>"
  score-invalid-amount: "&6FCE &8■ &cКоличество должно быть положительным числом!"
  score-invalid-operation: "&6FCE &8■ &cОперация должна быть 'plus' или 'minus'!"
  score-plus: "&6FCE &8■ &aДобавлено &6%amount%&a очков игроку &6%player%&a. Новый счёт: &6%newscore%"
  score-minus: "&6FCE &8■ &cУбрано &6%amount%&c очков у игрока &6%player%&c. Новый счёт: &6%newscore%"

database:
  enabled: false #Вкл/выкл подключения бд
  host: "127.0.0.1"
  port: 3306
  database: "fce"
  username: "root"
  password: "password"

top-settings:
  lines: 10 #Кол-во игроков в топе, действуют со всеми другими системами плагина.
  top-header: "&aТоп игроков по ивенту:"
  top-line: "&e%position%. &6%player% - &a%amount% %item%"
  top-empty: "&e%position%. &7N/A"